export const refinedTags = {
  "Couvent St. Etienne": [
    "11 x 15 cm",
    "1895-1913",
    "1905",
    "1905-1910",
    "1907",
    "1908- 1909",
    "1908-1909",
    "1909",
    "1909-1910",
    "1910",
    "1911",
    "1912",
    "1913",
    "1913-1914",
    "1914",
    "1920",
    "1921-1922",
    "1922",
    "1922-1924",
    "1923",
    "1923-1924",
    "1923-1925",
    "1924",
    "1925",
    "1926",
    "1928",
    "1929-1931",
    "1930",
    "1933",
    "1935",
    "1936-1938",
    "1936-39",
    "1937-1938",
    "1938",
    "4 x 4.5 cm",
    "4.5 x 10.7 cm",
    "A.  Barrois",
    "A. Jaussen",
    "Aboud",
    "Abu Ghosh",
    "Albert Einstein",
    "Amwâs",
    "Ascalon",
    "Ascalân",
    "Asdoud",
    "Ashdod",
    "Aujâh el-Hafir",
    "Aïn Sultân",
    "Aïn Unqur",
    "Beit Jemal",
    "Bethléem",
    "Bâb Sitti Maryam",
    "Cana",
    "Cathédrale russe",
    "Cathédrale éthiopienne",
    "Cité de David",
    "Consulat général de France",
    "Couvent Saint-Étienne",
    "Cédron",
    "Césarée Maritime",
    "Deir Dosi",
    "Dôme du Rocher",
    "Ecole biblique",
    "El-Aqsa",
    "Emmaüs-Nicopolis",
    "Esplanade des mosquées",
    "Galilée",
    "Gaza",
    "Gethsémani",
    "Grand négatif sur verre (13 x 18 cm)",
    "Haram",
    "Haram el-Sharif",
    "Harâm el-Khalîl",
    "Haïfa",
    "Hospice St Paul",
    "Hébron",
    "Jaffa",
    "Jemâlâ",
    "Juda",
    "Jéricho",
    "Jérusalem",
    "Jérusalemr",
    "Kafr Kanna",
    "Khirbet el-Fakhâkhîr",
    "La mer Morte",
    "Latroun",
    "Le Naby Musa",
    "Liban",
    "Lydda",
    "M. Bonnier",
    "M. Charles Prickartz",
    "Manuel Ferrero",
    "Mont Carmel",
    "Mont Garizim",
    "Moskobiyeh",
    "Mosquée",
    "Mt des Oliviers",
    "Musrara",
    "Mâr Elias",
    "Méditerranée",
    "Naby Rubin",
    "Naplouse",
    "Nazareth",
    "Naïm",
    "Notre-Dame de France",
    "Négatif sur verre. 11 x 15 cm",
    "Négatif verre 11 x 15 cm",
    "Négatif verre 9 x 12 cm",
    "Négeb",
    "Old City",
    "Paulus-Haus",
    "Pierre Benoit",
    "Pierre Benoitr",
    "Pierre Benoît",
    "Plan-film 8 x 11 cm",
    "Plan-film au format 9 x 12 cm",
    "Plaque 13 x 18 cm",
    "Plaque de verre",
    "Plaque de verre  4.5 x 10. 7 cm",
    "Plaque de verre  7 x 13 cm",
    "Plaque de verre 10 x 15 cm",
    "Plaque de verre 11 x 15",
    "Plaque de verre 11 x 15 cm",
    "Plaque de verre 13 x 18 cm",
    "Plaque de verre 18 x 24 cm",
    "Plaque de verre 24 x 30 cm",
    "Plaque de verre 9  x 12 cm",
    "Plaque de verre 9 x 12 cm",
    "Plaque de verre au format panoramique (8 x 18 cm)",
    "Porte",
    "Porte Bâb el-Zahar",
    "Porte de Damas",
    "Porte de Jaffa (Bâb el-Khâlil)",
    "Porte des Lions",
    "Porte d’Hérode",
    "Prodromos",
    "Pèlerinage CHRETIEN",
    "Pèlerinage musulman",
    "Pères Blancs",
    "Pères-Blancs",
    "Qouleh",
    "R. Savignac",
    "R. Tonneau",
    "R. de Vaux",
    "Ramlah",
    "Ramleh",
    "Rentis",
    "Safed",
    "Samarie",
    "Sheikh Qatrâwi",
    "St George Khoziba",
    "St Jean-d’Acre",
    "St Sépulcre",
    "St. Théodose",
    "Stella Maris",
    "Stéréoscopique",
    "Swafir el-Sharqiyeh",
    "Sébastiyah",
    "Sébastiyeh",
    "Taybeh",
    "Tibériade",
    "Tirage papier 9 x 12 cm",
    "Tirage papier. 9 x 12 cm",
    "Tombeau de la Vierge",
    "Tombeau des Patriarches",
    "Verre 11 x 15 cm",
    "Verre 18 x 24 cm",
    "Verre 7 x 13 cm",
    "Verre 9 x 12 cm",
    "Verre de 10 x 15 cm",
    "Village",
    "Village de Zakariyah",
    "al-Aqsa",
    "basilique",
    "basilique Ste Anne",
    "basilique de la Nativité",
    "basilique des Nations",
    "basilique du Pater Noster",
    "basilique du Éléona",
    "bateau",
    "birket el-Sultân",
    "byzantine",
    "colorimétrie",
    "couvent",
    "dominicain",
    "dominicains",
    "désert de Juda",
    "d’Asdud",
    "el-Aqsa",
    "esplanade des Mosquées",
    "feast of Saint Elijah",
    "format de 18 x 24 cm",
    "franciscaine",
    "la Vieille Ville",
    "la basilique franciscaine de l’Agonie",
    "la colline de l’Ophel",
    "la fête de la saint Élie",
    "la mer Morte",
    "la procession du Naby Musa",
    "la vieille ville",
    "lac",
    "lac de Tibériade",
    "le couvent des pères Carmes",
    "l’oasis",
    "mamelouke",
    "mer",
    "mer- Négatif 10 x 15 cm",
    "mer- Verre 9 x 12 cm",
    "monastère",
    "monastère grec-orthodoxe de St Jean-Baptiste",
    "montagne",
    "monument",
    "mosquée",
    "neige",
    "nécropole",
    "plan-film 6 x 9.5 cm",
    "plaque de verre 18 x 24 cm",
    "plaque de verre 24 x 30 cm",
    "plaque de verre 9 x 12 cm",
    "plaque de verre de grand format. 18 x 24 cm",
    "port",
    "pères assomptionnistes de Notre-Dame de France",
    "ruines",
    "stéréoscopique",
    "synagogue",
    "tirage papier (6.5 x 10.5 cm)",
    "tombe de Jacob",
    "tombe du prophète Moïse",
    "vallée du Cédron",
    "verre 10 x 15 cm",
    "verre 11 x 15 cm",
    "verre 18 x 24 cm (ciel réduit)",
    "verre 9 x 12 cm",
    "village",
    "ville",
    "wady Qelt",
    "église",
    "‛Akka",
  ],
  "Couvent St. Etienne /  Notre-Dame de France": [
    "1890-1900",
    "1895",
    "1898",
    "1905",
    "1910",
    "1933",
    "A.  Barrois",
    "Abou Ghosh",
    "American Colony Photographer",
    "Beit Jibrin",
    "Carmel de Ziph",
    "Galilée",
    "Germer-Durand",
    "Haïfa",
    "Jaffa",
    "Jenine",
    "Jifnah",
    "Kafr Kanna",
    "Khân  el-Ahmar",
    "Kirmil",
    "Mont Carmel",
    "Mosquée",
    "Mâr Eliâs",
    "Nazareth",
    "Plaque de verre 24 x 30 cm",
    "Plaque de verre 8 x 18 cm",
    "Plaque de verre 9 x 12 cm",
    "Plaque de verre grand format (24 x 30 cm)",
    "Samarie",
    "St Euthyme dominicains",
    "St Jean-d’Acre",
    "Tibériade",
    "Tirage papier de 24 cm",
    "Village",
    "Ville",
    "assomptionnistes de Notre-Dame de France",
    "byzantin",
    "byzantine",
    "désert de Juda",
    "franciscaine",
    "lac",
    "mer",
    "monastère",
    "montagne",
    "mosquée",
    "plaque de verre (18 x 24 cm. perdue)",
    "plaque de verre 24 x 30 cm",
    "plaque de verre de grand format (24 x 30 cm)",
    "port",
    "pères",
    "pères assomptionnistes de Notre-Dame de France",
    "sépia",
    "église",
    "‛Akka",
  ],
  "Couvent St. Etienne /  Sainte-Anne": [
    "15.5 x 8 cm",
    "1893",
    "1900",
    "1901",
    "1909",
    "1910",
    "1912",
    "1914",
    "1920",
    "Abu Ghosh",
    "Aïn Bettir",
    "Aïn Karem",
    "Battir",
    "Beit Jala",
    "Bethléem",
    "Béthanie",
    "Deir Hajla",
    "Herodium",
    "Hébron",
    "Jaffa",
    "Jourdain",
    "La vieille ville",
    "Lazariyeh",
    "Le Naby Musa",
    "Mt des Oliviers",
    "Plaque de verre",
    "Plaque de verre  7 x 13 cm",
    "Plaque de verre 10 x 15 cm",
    "Plaque de verre 13 x 18 cm",
    "Plaque de verre 6 x 8 cm",
    "Plaque de verre positive de format carré",
    "Porte",
    "Pères Blancs",
    "Pères Blancs de Ste Anne",
    "Pères-Blancs de Ste Anne",
    "St Gérasimos",
    "Tombeau de Rachel",
    "Tombeau des Patriarches",
    "Vallée du Jourdain",
    "basilique",
    "basilique de la Nativité",
    "désert de Juda",
    "fontaine",
    "grec orthodoxe",
    "grecs-catholiques",
    "la mer Morte",
    "la vieille ville",
    "mer",
    "monastère",
    "mosquée",
    "plaque de verre",
    "plaque de verre 6 x 9 cm",
    "pères Blancs de Ste Anne",
    "tombe de St Lazare",
    "tombe du prophète Moïse",
    "village",
    "église",
  ],
  "Couvent St. Etienne / Bethléem coloriée": [
    "American Colony Photographer",
    "basilique",
    "basilique de la Nativité",
  ],
  "Couvent St. Etienne / Charles Prickartz": [
    "1908-1909",
    "4.5 x 10.7 cm",
    "Arc Ecce Homo",
    "Artas",
    "Bethléem",
    "Campagne de Palestine",
    "Charles Prickartz",
    "Citerne",
    "Dames de Sion",
    "Ecce Homo",
    "Esplanade des Mosquées",
    "Fontaine",
    "Fontaine Qaït Bey",
    "Jules Prickarts",
    "Jules Prickartz",
    "Jérusalem",
    "Mamelouke",
    "Nawars",
    "Ortas",
    "Petit négatif  stéréoscopique",
    "Porte de Jaffa",
    "Puits",
    "Sabil",
    "Sabil  - Sébille",
    "Stéréoscopique 4.5 x 10.7",
    "Tanakés",
    "Urtas",
    "Via Dolorosa",
    "dominicains",
    "hortus conclusus",
    "la mer Morte",
    "mer",
    "petit négatif  stéréoscopique",
    "stéréoscopique (4.5 x 10.7 cm)",
  ],
  "Couvent St. Etienne / JOURDAIN COULEURS": ["la mer Morte"],
  "Couvent St. Etienne / Jesuit": [
    "Aïn Karem",
    "Bethléem",
    "Capharnaüm",
    "Galilée",
    "Hérodion",
    "Manuel Ferrero",
    "Négatif souple. rouleau pour appareil folding 9 x 12 cm",
    "Plan-film 9 x 12 cm",
    "Plan-film. 9 x 12 cm. 1930-1938",
    "basilique",
    "basilique de la Nativité",
    "synagogue",
    "église",
  ],
  "Couvent St. Etienne / Paulus-Haus": [
    "Jaffa",
    "Plaque de verre 10 x 15 cm",
    "R. Savignac 1907",
  ],
  "Couvent St. Etienne / The Sainte-Anne Collection": [
    "1921",
    "Bethléem",
    "Cédron",
    "Désert de Judée",
    "Manuel Ferrero",
    "Mar Saba",
    "Plaque de verre 14.5 x 18 cm",
    "Pères Blancs de Ste Anne",
    "Pères-Blancs de Ste Anne",
    "Tirage papier. 9 x 12 cm",
    "basilique",
    "monastère",
  ],
  "All collections": [
    "11 x 15 cm",
    "15.5 x 8 cm",
    "1890-1900",
    "1893",
    "1895",
    "1895-1913",
    "1898",
    "1900",
    "1901",
    "1905",
    "1905-1910",
    "1907",
    "1908- 1909",
    "1908-1909",
    "1909",
    "1909-1910",
    "1910",
    "1911",
    "1912",
    "1913",
    "1913-1914",
    "1914",
    "1920",
    "1921",
    "1921-1922",
    "1922",
    "1922-1924",
    "1923",
    "1923-1924",
    "1923-1925",
    "1924",
    "1925",
    "1926",
    "1928",
    "1929-1931",
    "1930",
    "1933",
    "1935",
    "1936-1938",
    "1936-39",
    "1937-1938",
    "1938",
    "4 x 4.5 cm",
    "4.5 x 10.7 cm",
    "A.  Barrois",
    "A. Jaussen",
    "Abou Ghosh",
    "Aboud",
    "Abu Ghosh",
    "Albert Einstein",
    "American Colony Photographer",
    "Amwâs",
    "Arc Ecce Homo",
    "Artas",
    "Ascalon",
    "Ascalân",
    "Asdoud",
    "Ashdod",
    "Aujâh el-Hafir",
    "Aïn Bettir",
    "Aïn Karem",
    "Aïn Sultân",
    "Aïn Unqur",
    "Battir",
    "Beit Jala",
    "Beit Jemal",
    "Beit Jibrin",
    "Bethléem",
    "Bâb Sitti Maryam",
    "Béthanie",
    "Campagne de Palestine",
    "Cana",
    "Capharnaüm",
    "Carmel de Ziph",
    "Cathédrale russe",
    "Cathédrale éthiopienne",
    "Charles Prickartz",
    "Citerne",
    "Cité de David",
    "Consulat général de France",
    "Couvent Saint-Étienne",
    "Cédron",
    "Césarée Maritime",
    "Dames de Sion",
    "Deir Dosi",
    "Deir Hajla",
    "Désert de Judée",
    "Dôme du Rocher",
    "Ecce Homo",
    "Ecole biblique",
    "El-Aqsa",
    "Emmaüs-Nicopolis",
    "Esplanade des Mosquées",
    "Esplanade des mosquées",
    "Fontaine",
    "Fontaine Qaït Bey",
    "Galilée",
    "Gaza",
    "Germer-Durand",
    "Gethsémani",
    "Grand négatif sur verre (13 x 18 cm)",
    "Haram",
    "Haram el-Sharif",
    "Harâm el-Khalîl",
    "Haïfa",
    "Herodium",
    "Hospice St Paul",
    "Hébron",
    "Hérodion",
    "Jaffa",
    "Jemâlâ",
    "Jenine",
    "Jifnah",
    "Jourdain",
    "Juda",
    "Jules Prickarts",
    "Jules Prickartz",
    "Jéricho",
    "Jérusalem",
    "Jérusalemr",
    "Kafr Kanna",
    "Khirbet el-Fakhâkhîr",
    "Khân  el-Ahmar",
    "Kirmil",
    "La mer Morte",
    "La vieille ville",
    "Latroun",
    "Lazariyeh",
    "Le Naby Musa",
    "Liban",
    "Lydda",
    "M. Bonnier",
    "M. Charles Prickartz",
    "Mamelouke",
    "Manuel Ferrero",
    "Mar Saba",
    "Mont Carmel",
    "Mont Garizim",
    "Moskobiyeh",
    "Mosquée",
    "Mt des Oliviers",
    "Musrara",
    "Mâr Elias",
    "Mâr Eliâs",
    "Méditerranée",
    "Naby Rubin",
    "Naplouse",
    "Nawars",
    "Nazareth",
    "Naïm",
    "Notre-Dame de France",
    "Négatif souple. rouleau pour appareil folding 9 x 12 cm",
    "Négatif sur verre. 11 x 15 cm",
    "Négatif verre 11 x 15 cm",
    "Négatif verre 9 x 12 cm",
    "Négeb",
    "Old City",
    "Ortas",
    "Paulus-Haus",
    "Petit négatif  stéréoscopique",
    "Pierre Benoit",
    "Pierre Benoitr",
    "Pierre Benoît",
    "Plan-film 8 x 11 cm",
    "Plan-film 9 x 12 cm",
    "Plan-film au format 9 x 12 cm",
    "Plan-film. 9 x 12 cm. 1930-1938",
    "Plaque 13 x 18 cm",
    "Plaque de verre",
    "Plaque de verre  4.5 x 10. 7 cm",
    "Plaque de verre  7 x 13 cm",
    "Plaque de verre 10 x 15 cm",
    "Plaque de verre 11 x 15",
    "Plaque de verre 11 x 15 cm",
    "Plaque de verre 13 x 18 cm",
    "Plaque de verre 14.5 x 18 cm",
    "Plaque de verre 18 x 24 cm",
    "Plaque de verre 24 x 30 cm",
    "Plaque de verre 6 x 8 cm",
    "Plaque de verre 8 x 18 cm",
    "Plaque de verre 9  x 12 cm",
    "Plaque de verre 9 x 12 cm",
    "Plaque de verre au format panoramique (8 x 18 cm)",
    "Plaque de verre grand format (24 x 30 cm)",
    "Plaque de verre positive de format carré",
    "Porte",
    "Porte Bâb el-Zahar",
    "Porte de Damas",
    "Porte de Jaffa",
    "Porte de Jaffa (Bâb el-Khâlil)",
    "Porte des Lions",
    "Porte d’Hérode",
    "Prodromos",
    "Puits",
    "Pèlerinage CHRETIEN",
    "Pèlerinage musulman",
    "Pères Blancs",
    "Pères Blancs de Ste Anne",
    "Pères-Blancs",
    "Pères-Blancs de Ste Anne",
    "Qouleh",
    "R. Savignac",
    "R. Savignac 1907",
    "R. Tonneau",
    "R. de Vaux",
    "Ramlah",
    "Ramleh",
    "Rentis",
    "Sabil",
    "Sabil  - Sébille",
    "Safed",
    "Samarie",
    "Sheikh Qatrâwi",
    "St Euthyme dominicains",
    "St George Khoziba",
    "St Gérasimos",
    "St Jean-d’Acre",
    "St Sépulcre",
    "St. Théodose",
    "Stella Maris",
    "Stéréoscopique",
    "Stéréoscopique 4.5 x 10.7",
    "Swafir el-Sharqiyeh",
    "Sébastiyah",
    "Sébastiyeh",
    "Tanakés",
    "Taybeh",
    "Tibériade",
    "Tirage papier 9 x 12 cm",
    "Tirage papier de 24 cm",
    "Tirage papier. 9 x 12 cm",
    "Tombeau de Rachel",
    "Tombeau de la Vierge",
    "Tombeau des Patriarches",
    "Urtas",
    "Vallée du Jourdain",
    "Verre 11 x 15 cm",
    "Verre 18 x 24 cm",
    "Verre 7 x 13 cm",
    "Verre 9 x 12 cm",
    "Verre de 10 x 15 cm",
    "Via Dolorosa",
    "Village",
    "Village de Zakariyah",
    "Ville",
    "al-Aqsa",
    "assomptionnistes de Notre-Dame de France",
    "basilique",
    "basilique Ste Anne",
    "basilique de la Nativité",
    "basilique des Nations",
    "basilique du Pater Noster",
    "basilique du Éléona",
    "bateau",
    "birket el-Sultân",
    "byzantin",
    "byzantine",
    "colorimétrie",
    "couvent",
    "dominicain",
    "dominicains",
    "désert de Juda",
    "d’Asdud",
    "el-Aqsa",
    "esplanade des Mosquées",
    "feast of Saint Elijah",
    "fontaine",
    "format de 18 x 24 cm",
    "franciscaine",
    "grec orthodoxe",
    "grecs-catholiques",
    "hortus conclusus",
    "la Vieille Ville",
    "la basilique franciscaine de l’Agonie",
    "la colline de l’Ophel",
    "la fête de la saint Élie",
    "la mer Morte",
    "la procession du Naby Musa",
    "la vieille ville",
    "lac",
    "lac de Tibériade",
    "le couvent des pères Carmes",
    "l’oasis",
    "mamelouke",
    "mer",
    "mer- Négatif 10 x 15 cm",
    "mer- Verre 9 x 12 cm",
    "monastère",
    "monastère grec-orthodoxe de St Jean-Baptiste",
    "montagne",
    "monument",
    "mosquée",
    "neige",
    "nécropole",
    "petit négatif  stéréoscopique",
    "plan-film 6 x 9.5 cm",
    "plaque de verre",
    "plaque de verre (18 x 24 cm. perdue)",
    "plaque de verre 18 x 24 cm",
    "plaque de verre 24 x 30 cm",
    "plaque de verre 6 x 9 cm",
    "plaque de verre 9 x 12 cm",
    "plaque de verre de grand format (24 x 30 cm)",
    "plaque de verre de grand format. 18 x 24 cm",
    "port",
    "pères",
    "pères Blancs de Ste Anne",
    "pères assomptionnistes de Notre-Dame de France",
    "ruines",
    "stéréoscopique",
    "stéréoscopique (4.5 x 10.7 cm)",
    "synagogue",
    "sépia",
    "tirage papier (6.5 x 10.5 cm)",
    "tombe de Jacob",
    "tombe de St Lazare",
    "tombe du prophète Moïse",
    "vallée du Cédron",
    "verre 10 x 15 cm",
    "verre 11 x 15 cm",
    "verre 18 x 24 cm (ciel réduit)",
    "verre 9 x 12 cm",
    "village",
    "ville",
    "wady Qelt",
    "église",
    "‛Akka",
  ],
};

export const collections = [
  "All collections",
  "Couvent St. Etienne",
  "Couvent St. Etienne / Charles Prickartz",
  "Couvent St. Etienne /  Sainte-Anne",
  "Couvent St. Etienne / Jesuit",
  "Couvent St. Etienne / The Sainte-Anne Collection",
  "Couvent St. Etienne /  Notre-Dame de France",
  "Couvent St. Etienne / Paulus-Haus",
  "Couvent St. Etienne / JOURDAIN COULEURS",
  "Couvent St. Etienne / Bethléem coloriée",
];

export const collectionWCount = [
  { name: "All collections", count: 189 },
  { name: "Couvent St. Etienne", count: 139 },
  { name: "Couvent St. Etienne / Charles Prickartz", count: 9 },
  { name: "Couvent St. Etienne /  Sainte-Anne", count: 16 },
  { name: "Couvent St. Etienne / Jesuit", count: 3 },
  { name: "Couvent St. Etienne / The Sainte-Anne Collection", count: 2 },
  { name: "Couvent St. Etienne /  Notre-Dame de France", count: 18 },
  { name: "Couvent St. Etienne / Paulus-Haus", count: 0 },
  { name: "Couvent St. Etienne / JOURDAIN COULEURS", count: 1 },
  { name: "Couvent St. Etienne / Bethléem coloriée", count: 1 },
];
