export const tags = [
  "11 x 15 cm",
  "15,5 x 8 cm",
  "1890-1900",
  "1893",
  "1895",
  "1895-1913",
  "1898",
  "1900",
  "1901",
  "1905",
  "1905-1910",
  "1907",
  "1908- 1909",
  "1908-1909",
  "1909",
  "1909-1910",
  "1910",
  "1911",
  "1912",
  "1913",
  "1913-1914",
  "1914",
  "1920",
  "1921",
  "1921-1922",
  "1922",
  "1922-1924",
  "1923",
  "1923-1924",
  "1923-1925",
  "1924",
  "1925",
  "1926",
  "1928",
  "1929-1931",
  "1930",
  "1933",
  "1935",
  "1936-1938",
  "1936-39",
  "1937-1938",
  "1938",
  "4 x 4,5 cm",
  "4,5 x 10,7 cm",
  "A.  Barrois",
  "A. Jaussen",
  "Abou Ghosh",
  "Aboud",
  "Abu Ghosh",
  "Albert Einstein",
  "American Colony Photographer",
  "Amwâs",
  "Arc Ecce Homo",
  "Artas",
  "Ascalon",
  "Ascalân",
  "Asdoud",
  "Ashdod",
  "Aujâh el-Hafir",
  "Aïn Bettir",
  "Aïn Karem",
  "Aïn Sultân",
  "Aïn Unqur",
  "Battir",
  "Beit Jala",
  "Beit Jemal",
  "Beit Jibrin",
  "Bethléem",
  "Bâb Sitti Maryam",
  "Béthanie",
  "Campagne de Palestine",
  "Cana",
  "Capharnaüm",
  "Carmel de Ziph",
  "Cathédrale russe",
  "Cathédrale éthiopienne",
  "Charles Prickartz",
  "Citerne",
  "Cité de David",
  "Consulat général de France",
  "Couvent Saint-Étienne",
  "Cédron",
  "Césarée Maritime",
  "Dames de Sion",
  "Deir Dosi",
  "Deir Hajla",
  "Désert de Judée",
  "Dôme du Rocher",
  "Ecce Homo",
  "Ecole biblique",
  "El-Aqsa",
  "Emmaüs-Nicopolis",
  "Esplanade des Mosquées",
  "Esplanade des mosquées",
  "Fontaine",
  "Fontaine Qaït Bey",
  "Galilée",
  "Gaza",
  "Germer-Durand",
  "Gethsémani",
  "Grand négatif sur verre (13 x 18 cm)",
  "Haram",
  "Haram el-Sharif",
  "Harâm el-Khalîl",
  "Haïfa",
  "Herodium",
  "Hospice St Paul",
  "Hébron",
  "Hérodion",
  "Jaffa",
  "Jemâlâ",
  "Jenine",
  "Jifnah",
  "Jourdain",
  "Juda",
  "Jules Prickarts",
  "Jules Prickartz",
  "Jéricho",
  "Jérusalem",
  "Jérusalemr",
  "Kafr Kanna",
  "Khirbet el-Fakhâkhîr",
  "Khân  el-Ahmar",
  "Kirmil",
  "La mer Morte",
  "La vieille ville",
  "Latroun",
  "Lazariyeh",
  "Le Naby Musa",
  "Liban",
  "Lydda",
  "M. Bonnier",
  "M. Charles Prickartz",
  "Mamelouke",
  "Manuel Ferrero",
  "Mar Saba",
  "Mont Carmel",
  "Mont Garizim",
  "Moskobiyeh",
  "Mosquée",
  "Mt des Oliviers",
  "Musrara",
  "Mâr Elias",
  "Mâr Eliâs",
  "Méditerranée",
  "Naby Rubin",
  "Naplouse",
  "Nawars",
  "Nazareth",
  "Naïm",
  "Notre-Dame de France",
  "Négatif souple, rouleau pour appareil folding 9 x 12 cm",
  "Négatif sur verre, 11 x 15 cm",
  "Négatif verre 11 x 15 cm",
  "Négatif verre 9 x 12 cm",
  "Négeb",
  "Old City",
  "Ortas",
  "Paulus-Haus",
  "Petit négatif  stéréoscopique",
  "Pierre Benoit",
  "Pierre Benoitr",
  "Pierre Benoît",
  "Plan-film 8 x 11 cm",
  "Plan-film 9 x 12 cm",
  "Plan-film au format 9 x 12 cm",
  "Plan-film, 9 x 12 cm, 1930-1938",
  "Plaque 13 x 18 cm",
  "Plaque de verre",
  "Plaque de verre  4,5 x 10, 7 cm",
  "Plaque de verre  7 x 13 cm",
  "Plaque de verre 10 x 15 cm",
  "Plaque de verre 11 x 15",
  "Plaque de verre 11 x 15 cm",
  "Plaque de verre 13 x 18 cm",
  "Plaque de verre 14,5 x 18 cm",
  "Plaque de verre 18 x 24 cm",
  "Plaque de verre 24 x 30 cm",
  "Plaque de verre 6 x 8 cm",
  "Plaque de verre 8 x 18 cm",
  "Plaque de verre 9  x 12 cm",
  "Plaque de verre 9 x 12 cm",
  "Plaque de verre au format panoramique (8 x 18 cm)",
  "Plaque de verre grand format (24 x 30 cm)",
  "Plaque de verre positive de format carré",
  "Porte",
  "Porte Bâb el-Zahar",
  "Porte de Damas",
  "Porte de Jaffa",
  "Porte de Jaffa (Bâb el-Khâlil)",
  "Porte des Lions",
  "Porte d’Hérode",
  "Prodromos",
  "Puits",
  "Pèlerinage CHRETIEN",
  "Pèlerinage musulman",
  "Pères Blancs",
  "Pères Blancs de Ste Anne",
  "Pères-Blancs",
  "Pères-Blancs de Ste Anne",
  "Qouleh",
  "R. Savignac",
  "R. Savignac 1907",
  "R. Tonneau",
  "R. de Vaux",
  "Ramlah",
  "Ramleh",
  "Rentis",
  "Sabil",
  "Sabil  - Sébille",
  "Safed",
  "Samarie",
  "Sheikh Qatrâwi",
  "St Euthyme dominicains",
  "St George Khoziba",
  "St Gérasimos",
  "St Jean-d’Acre",
  "St Sépulcre",
  "St. Théodose",
  "Stella Maris",
  "Stéréoscopique",
  "Stéréoscopique 4,5 x 10,7",
  "Swafir el-Sharqiyeh",
  "Sébastiyah",
  "Sébastiyeh",
  "Tanakés",
  "Taybeh",
  "Tibériade",
  "Tirage papier 9 x 12 cm",
  "Tirage papier de 24 cm",
  "Tirage papier, 9 x 12 cm",
  "Tombeau de Rachel",
  "Tombeau de la Vierge",
  "Tombeau des Patriarches",
  "Urtas",
  "Vallée du Jourdain",
  "Verre 11 x 15 cm",
  "Verre 18 x 24 cm",
  "Verre 7 x 13 cm",
  "Verre 9 x 12 cm",
  "Verre de 10 x 15 cm",
  "Via Dolorosa",
  "Village",
  "Village de Zakariyah",
  "Ville",
  "al-Aqsa",
  "assomptionnistes de Notre-Dame de France",
  "basilique",
  "basilique Ste Anne",
  "basilique de la Nativité",
  "basilique des Nations",
  "basilique du Pater Noster",
  "basilique du Éléona",
  "bateau",
  "birket el-Sultân",
  "byzantin",
  "byzantine",
  "colorimétrie",
  "couvent",
  "dominicain",
  "dominicains",
  "désert de Juda",
  "d’Asdud",
  "el-Aqsa",
  "esplanade des Mosquées",
  "feast of Saint Elijah",
  "fontaine",
  "format de 18 x 24 cm",
  "franciscaine",
  "grec orthodoxe",
  "grecs-catholiques",
  "hortus conclusus",
  "la Vieille Ville",
  "la basilique franciscaine de l’Agonie",
  "la colline de l’Ophel",
  "la fête de la saint Élie",
  "la mer Morte",
  "la procession du Naby Musa",
  "la vieille ville",
  "lac",
  "lac de Tibériade",
  "le couvent des pères Carmes",
  "l’oasis",
  "mamelouke",
  "mer",
  "mer- Négatif 10 x 15 cm",
  "mer- Verre 9 x 12 cm",
  "monastère",
  "monastère grec-orthodoxe de St Jean-Baptiste",
  "montagne",
  "monument",
  "mosquée",
  "neige",
  "nécropole",
  "petit négatif  stéréoscopique",
  "plan-film 6 x 9,5 cm",
  "plaque de verre",
  "plaque de verre (18 x 24 cm, perdue)",
  "plaque de verre 18 x 24 cm",
  "plaque de verre 24 x 30 cm",
  "plaque de verre 6 x 9 cm",
  "plaque de verre 9 x 12 cm",
  "plaque de verre de grand format (24 x 30 cm)",
  "plaque de verre de grand format, 18 x 24 cm",
  "port",
  "pères",
  "pères Blancs de Ste Anne",
  "pères assomptionnistes de Notre-Dame de France",
  "ruines",
  "stéréoscopique",
  "stéréoscopique (4,5 x 10,7 cm)",
  "synagogue",
  "sépia",
  "tirage papier (6,5 x 10,5 cm)",
  "tombe de Jacob",
  "tombe de St Lazare",
  "tombe du prophète Moïse",
  "vallée du Cédron",
  "verre 10 x 15 cm",
  "verre 11 x 15 cm",
  "verre 18 x 24 cm (ciel réduit)",
  "verre 9 x 12 cm",
  "village",
  "ville",
  "wady Qelt",
  "église",
  "‛Akka",
];

export const collections = [
  "All collections",
  "Couvent St. Etienne",
  "Couvent St. Etienne / Charles Prickartz",
  "Couvent St. Etienne /  Sainte-Anne",
  "Couvent St. Etienne / Jesuit",
  "Couvent St. Etienne / The Sainte-Anne Collection ",
  "Couvent St. Etienne /  Notre-Dame de France",
  "Couvent St. Etienne / Paulus-Haus",
  "Couvent St. Etienne / JOURDAIN COULEURS",
  "Couvent St. Etienne / Bethléem coloriée",
];
